package com.sample.rules
 
import com.sample.DroolsTest.Message;

// rule的名称时唯一的
rule "Hello World"
    when
        m : Message( status == Message.HELLO, myMessage : message )
    then
        System.out.println( myMessage );
        m.setMessage( "Goodbye cruel world" );
        m.setStatus( Message.GOODBYE );
        //update( m );
        System.out.println("Modify after : " + m.getStatus());
end

rule "GoodBye"
    when
        Message( status == Message.GOODBYE, myMessage : message )
    then
        System.out.println( myMessage );
end
